// @ts-nocheck
const assert = require('assert');
const { makeRuntime } = require('./regressions.test');
const { imageLifecycleRuntime, cleanup, replaceReference, matches } = require('../shared/image-lifecycle');
const { adminEndpoint } = require('../shared/admin');
const { toPublicError } = require('../shared/errors');
const old = 'cloud://test.bucket/admin/products/old.jpg';
const next = 'cloud://test.bucket/admin/products/new.webp';
async function run() {
  const metadata = makeRuntime();
  metadata.records.products['product-1'].images = [next];
  metadata.records.homeContents = { 'home.page-config': { _id: 'home.page-config', payload: { banners: [{ productId: 'product-1', image: next }], sections: [{ productIds: ['product-1'] }] } } };
  metadata.records.adminMembers = { admin: { _id: 'admin', uid: 'admin', status: 'active', roles: ['superadmin'] } };
  const transaction = metadata.db.runTransaction;
  let transactions = 0;
  metadata.db.runTransaction = (fn) => { transactions++; return transaction(fn); };
  await adminEndpoint({}, { auth: { uid: 'admin' } }, metadata, 'products.update', { id: 'product-1', status: 'inactive' });
  assert.strictEqual(metadata.records.products['product-1'].status, 'inactive');
  assert.strictEqual(metadata.records.homeContents['home.page-config'].payload.banners[0].productId, '');
  assert.strictEqual(transactions, 1, 'downlisting uses only the business transaction');
  assert(!metadata.writes.some((write) => write.collection === 'settings'), 'unchanged image references do not contend on the cleanup fence');
  await imageLifecycleRuntime(metadata).db.collection('skus').doc('sku-new').update({ stockQuantity: 9 });
  assert.strictEqual(transactions, 1, 'stock-only updates do not start image transactions');
  assert.strictEqual(metadata.records.skus['sku-new'].stockQuantity, 9);
  assert.strictEqual(toPublicError(new Error('Transaction request failed')).code, 'INTERNAL_ERROR');
  assert.strictEqual(toPublicError(Object.assign(new Error('write conflict'), { code: 'DATABASE_TRANSACTION_CONFLICT' })).code, 'CONFLICT');
  const runtime = makeRuntime();
  const deleted = [];
  runtime.app = { deleteFile: async ({fileList}) => { deleted.push(...fileList); return {fileList:fileList.map(fileID=>({fileID,code:'SUCCESS'}))}; } };
  runtime.records.products['product-1'].images = [old];
  runtime.records.orders.history = {_id:'history',items:[{image:old}]};
  const wrapped = imageLifecycleRuntime(runtime);
  await wrapped.db.collection('products').doc('product-1').update({images:[next]});
  assert(wrapped.removedImages.has(old));
  assert.deepStrictEqual((await cleanup(runtime,{fileList:[old]})).retained,[old]);
  assert.strictEqual(deleted.length,0,'historical order protects shared original');
  await replaceReference(runtime,{oldFileID:old,newFileID:next,source:'orders',id:'history'});
  assert.strictEqual(runtime.records.orders.history.items[0].image,next);
  await wrapped.db.collection('products').doc('product-1').update({images:[old]});
  assert.deepStrictEqual(runtime.records.products['product-1'].images,[next],'stale clients use migrated image');
  assert.deepStrictEqual((await cleanup(runtime,{fileList:[old]})).deleted,[old]);
  const unused = 'cloud://test.bucket/admin/products/unused.jpg';
  await cleanup(runtime,{fileList:[unused]});
  await assert.rejects(()=>wrapped.db.collection('products').doc('product-1').update({images:[unused]}),e=>e.code==='CONFLICT');
  const failure = makeRuntime();
  failure.app = {deleteFile:async()=>{throw new Error('must not delete');}};
  const originalCollection = failure.db.collection;
  failure.db.collection = name => name==='orders' ? {orderBy(){throw new Error('scan failed');}} : originalCollection(name);
  await assert.rejects(()=>cleanup(failure,{fileList:[old]}),/scan failed/);
  const race = makeRuntime();
  race.app = {deleteFile:async()=>{throw new Error('must not delete after concurrent write');}};
  const raceTransaction = race.db.runTransaction;
  race.db.runTransaction = fn => { race.records.settings = {'__image_cleanup_control':{version:10}}; return raceTransaction(fn); };
  await assert.rejects(()=>cleanup(race,{fileList:[old]}),e=>e.code==='CONFLICT');
  assert(matches('https://bucket.tcb.qcloud.la/admin/products/old.jpg?sign=a',old));
  assert(!matches('https://bucket.evil.com/admin/products/old.jpg',old));
  console.log('PASS image cleanup preserves history, fails closed, fences writes and migrates stale references');
}
module.exports = {run};
